# Generated by Django 4.2.9 on 2026-03-17 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('generic_name', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup'), ('injection', 'Injection'), ('cream', 'Cream'), ('drops', 'Drops'), ('inhaler', 'Inhaler'), ('powder', 'Powder'), ('other', 'Other')], default='tablet', max_length=50)),
                ('manufacturer', models.CharField(max_length=255)),
                ('batch_number', models.CharField(db_index=True, max_length=100)),
                ('expiry_date', models.DateField(db_index=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.IntegerField(default=0)),
                ('min_stock_threshold', models.IntegerField(default=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicines', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Medicine',
                'verbose_name_plural': 'Medicines',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name', 'batch_number'], name='medicines_m_name_c42f06_idx'), models.Index(fields=['expiry_date'], name='medicines_m_expiry__a86637_idx')],
            },
        ),
    ]
